### ISSUE TITLE
Lab Report 2 Feedback 

### ISSUE THREAD

**Issue by mrkylesmith** [jackthomas00/cse15l-lab-reports#2]
**Bug/Input 1**
- [x] Commit screenshot for bug/input 1
- [x] Link to test file for bug/input 1
- [] Symptom shown as command + output for bug/input 1
- You should include the command in your screenshot.
- [] Description of relationship between bug, symptom, and input for bug/input 1
- You should describe the change you made in the commit screenshot as well. (ie. the fix)

**Bug/Input 2**
- [x] Commit screenshot for bug/input 2
- [x] Link to test file for bug/input 2
- [] Symptom shown as command + output for bug/input 2
- Please include command in screenshot also. 
- [x] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [x] Commit screenshot for bug/input 3
- [x] Link to test file for bug/input 3
- [] Symptom shown as command + output for bug/input 3
- Include command here also in screenshot.
- [] Description of relationship between bug, symptom, and input for bug/input 3
- On all three of these descriptions you should include a sentence about what you changed in your commit screenshot in order to handle the input. 

Additional comments from your grader:
Good job! Please see my comments above. 

Feel free to comment below if you have any questions about the rubric/feedback.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by jackthomas00** [comment]
Can I write as like a code instead of getting new screen shot. So show command using the `$ javac -cp blah MDP.java`

**Comment by mrkylesmith** [comment]
I see you added the screenshots of your command + output.  Looks good. Your score has been updated.
