### ISSUE TITLE
Lab Report 5 Feedback

### ISSUE THREAD

**Issue by JIzabal** [jackthomas00/cse15l-lab-reports#5]
Here is your feedback for Lab Report 5:

- [x] Explains how tests with different results were found (`diff`, manual search, etc)

Test 1:

- [x] Describes which, if any, implementation is correct by showing both actual outputs and indicating what the expected output is
- [x] Describes bug in code for one of the incorrect implementation and shows the code that should be fixed.
  - Show where in the incorrect implementation that the code should be fixed 

Test 2:

- [x] Describes which, if any, implementation is correct by showing both actual outputs and indicating what the expected output is
- [x] Describes bug in code for one of the incorrect implementation and shows the code that should be fixed.

Additional comments from your grader:

Feel free to comment below any questions about the rubric/feedback

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by JIzabal** [comment]
Nice work!

**Comment by jackthomas00** [comment]
Thanks. Is there a way to tell what grade I got in class before it comes out. I think I only missed 1 lab participation.

**Comment by jackthomas00** [comment]
Also what is final tomorrow and is it necessary?

**Comment by JIzabal** [comment]
The best way to tell would be to look at the grading criteria in the [syllabus](https://ucsd-cse15l-w22.github.io/syllabus/#grading). You can also look at the grade summary on Gradescope to see your progress up until week 10. Although it isn't your final grade because some assignments were graded after it, this should also give you an idea as to what grade you can expect. As for the final, I don't recall there being any mention of a final, and based on this [Piazza post](https://piazza.com/class/kxs0toocqhv4og?cid=573) I don't think there is one. However, it'd be good for you to check on Piazza or in lecture where this might've been mentioned already. If you have any other logistical questions, feel free to ask on Piazza to ensure that you get the most accurate answer. I hope the rest of your finals go well and have a great spring break!
